project:
  type: website
  output-dir: docs
  preview: 
    port: 1200
    browser: true

website:
  title: "Coastal Ecosystem Accounting"
  back-to-top-navigation: true
  search: true
  navbar: 
    background: white
    search: true
    left:
      - text: "About"
        href: index.qmd
      - text: "Data Management Plan"
        href: dmp.qmd
      - text: "Data Processing"
        menu:
          - text: "<u>Global</u>"
          - text: "Process MHI Moku Vectors"
            href: data_processing/global/process_mhi_moku_vectors.qmd
  
          - text: "<br><u>Extents and Conditions</u>"
          - text: "Overview"
            href: data_processing/extents_and_conditions/extents_and_conditions.qmd
          - text: "Process Coral Cover"
            href: data_processing/extents_and_conditions/process_coral_cover.qmd
  
          - text: "<br><u>Fisheries Valuation</u>"
          - text: "Overview"
            href: data_processing/fisheries_valuation/fisheries_valuation.qmd
          - text: "Process Catch Data"
            href: data_processing/fisheries_valuation/process_catch_data.qmd
  
      - text: "Applications"
        menu:
          - text: "Extents and Conditions"
            href: extents_and_conditions/extents_and_conditions_app.qmd
          - text: "Fisheries Valuation"
            href: fisheries/fisheries_app.qmd
  page-footer: |
    ![](/assets/logos/uhm_logo.png){width=40%}
    <br><br>
        
format:
  html:
    theme: litera
    page-layout: full
    link-external-newwindow: true
    code-fold: true
    code-overflow: wrap
    code-annotations: hover
    # code-tools: true
    smooth-scroll: true
    toc: true
    toc-depth: 4
    toc-location: left

execute:
  message: false
  warning: false
  echo: true