---
format:
  gfm:
    toc: true
    toc-title: "Contents"
---

# The Hawaiian Model: Assessing, Valuing, and Integrating Nature’s Services for Institutional Conservation Choices

## Project Structure

```markdown
📂 coastal_ecosystem_accounting
├── 📄 LICENSE
├── 📄 README.md
├── 📄 README.qmd
├── 📄 _quarto.yml
├── 📄 about.qmd
└── 📂 apps/
│  └── 📂 extents_and_conditions/
│    ├── 📄 extents_and_conditions_app.qmd
│  └── 📂 fisheries_valuation/
│    ├── 📄 fisheries_valuation_app.qmd
└── 📂 assets/
│  └── 📂 logos/
│  └── 📂 styles/
└── 📂 data/
└── 📂 data_processing/
│  └── 📂 extents_and_conditions/
│  └── 📂 fisheries_valuation/
├── 📄 dmp.qmd
└── 📂 docs/
└── 📂 documentation/
├── 📄 index.qmd
├── 📄 manifest.json
├── 📄 project.Rproj
└── 📂 renv/
└── 📄 renv.lock
```
## R Session

```{r packages, echo=FALSE, message=FALSE, warning=FALSE}
# Load required libraries
if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
if (!requireNamespace("pak", quietly = TRUE)) install.packages("pak")

library(renv)
library(pak)
```

```{r session-info, echo=FALSE}
sessionInfo()
```